/****************************************************************
This file has been automatically generated by the pattern compiler
- DO NOT EDIT
*****************************************************************/

#define TWO_ARG_PATTERN_GOSUB_UINST

class Pattern;
class ScanPattern;
extern Pattern *example1;
