// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _PATTERN1_H_
#define _PATTERN1_H_

EXTERN_PATTERN( CFG_set_PAT )
EXTERN_PATTERN( CFG_get_PAT )
EXTERN_PATTERN( address_pat )
EXTERN_PATTERN( int_clk_read_pat )
EXTERN_PATTERN( int_clk_write_pat )
EXTERN_PATTERN( reset_set_cycle_pat )
EXTERN_PATTERN( int_clk_write_one_address_pat )
EXTERN_PATTERN( reset_set_single_cell_cycle_pat )
EXTERN_PATTERN( old_fastest_write_test_pattern )
EXTERN_PATTERN( fastest_read_test_pattern )
EXTERN_PATTERN( staircase_down_external_write_test_pattern )
EXTERN_PATTERN( single_external_write_test_pattern )
EXTERN_PATTERN( double_staircase_down_external_write_test_pattern )
EXTERN_PATTERN( quadruple_staircase_down_external_write_test_pattern )
EXTERN_PATTERN( fastest_write_test_pattern )
EXTERN_PATTERN( debug_time_test_pattern )
EXTERN_PATTERN( force_V_pat )
EXTERN_PATTERN( reset_set_01_cycle_pat )
EXTERN_PATTERN( fastest_write_test_pattern_slope_version_pattern )
EXTERN_PATTERN( fastest_write_rst_test_pattern )

#endif
